export const UPDATE_EMPLOYEE_LIST = "UPDATE_EMPLOYEE_LIST";
export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE";
export const SET_CURRENT_EMPLOYEE = "SET_CURRENT_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const LOADING = "LOADING";

export const ADD_SELECTED = "ADD_SELECTED";
export const REMOVE_SELECTED= "REMOVE_SELECTED";

